Adicionando atividades da semana 1
fga-eps-mds/2023-2-PCGO-Doc pull request #2
Opened 2023-09-06 14:57 UTC by AntonioRangelC

2023-09-06 18:00 UTC, vitordiniz25 approved these changes
LTGM!

2023-09-06 19:56 UTC, guilhermedfs requested changes
Faltou falar sobre a a criação do repositório de documentação.

2023-09-06 19:56 UTC, guilhermedfs commented on docs/Relatórios/semana1.md
> +Quadro de Conhecimento dos MDS:
Acho que seria bom descrever o que seria esse quadro de conhecimento.

2023-09-06 19:56 UTC, guilhermedfs commented on docs/Relatórios/semana1.md
> +### Levantamento do quadro de Conhecimento
Seria bom criar um texto dando o contexto, além de falar o objetivo desse levantamento.

2023-09-06 20:00 UTC, guilhermedfs commented on docs/Relatórios/semana1.md
> +
Seria interessante citar que nos apresentamos para os alunos de MDS.

2023-09-06 21:18 UTC, guilhermedfs commented on docs/Relatórios/semana1.md
> +![Quadro de Conhecimento dos EPS](../assets/quadro_conhecimento_eps.png)
Como o pessoal de MDS n terminou de preencher, acho melhor adicionar os quadros como tabela para que quando eles terminem isso seja refletido no documento.

2023-09-12 13:37 UTC, julisous commented
Documento revisado

2023-09-12 13:38 UTC, julisous commented
Documento revisado

2023-09-12 13:41 UTC, julisous approved these changes
Estou de acordo com as alterações e creio que tudo necessário para essa semana já foi colocado.

2023-09-12 14:23 UTC, merged